%Set preferences with setdbprefs.
setdbprefs('DataReturnFormat', 'numeric');
setdbprefs('NullNumberRead', 'NaN');
setdbprefs('NullStringRead', 'null');


%Make connection to database.  Note that the password has been omitted.
%Using ODBC driver.
conn = database('05Full', '', '');

%Read data from database.
curs = exec(conn, ['SELECT 	FiltroA_Total.Data'...
    ' ,	FiltroA_Total.Hora'...
    ' ,	FiltroA_Total.IP'...
    ' ,	FiltroA_Total.Metodo'...
    ' ,	FiltroA_Total.URI'...
    ' ,	FiltroA_Total.Status'...
    ' ,	FiltroA_Total.Bytes'...
    ' ,	FiltroA_Total.Tempo'...
    ' ,	FiltroA_Total.URL'...
    ' ,	FiltroA_Total.UserAgent'...
    ' ,	FiltroA_Total.Cookie'...
    ' ,	FiltroA_Total.WAFinfo'...
    ' ,	FiltroA_Total.UserAgentBrowser'...
    ' ,	FiltroA_Total.Origem'...
    ' ,	FiltroA_Total.Acao'...
    ' ,	FiltroA_Total.Servico'...
    ' ,	FiltroA_Total.portOrigem'...
    ' ,	FiltroA_Total.Destino'...
    ' ,	FiltroA_Total.Protocolo'...
    ' ,	FiltroA_Total.Regra'...
    ' ,	FiltroA_Total.Informacao'...
    ' ,	FiltroA_Total.Produto'...
    ' FROM 	WAFIPS05.dbo.FiltroA_Total ']);

curs = fetch(curs);
close(curs);

%Assign data to output variable
untitled = curs.Data;

%Close database connection.
close(conn);

%Clear variables
clear curs conn